version: '3.8'

name: payment-gateway
services:
  postgres-payment-gateway-db:
    image: docker.io/bitnami/postgresql
    restart: always
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=transactions
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/bitnami/postgresql/data
  redis-payment-gateway-db:
    image: docker.io/bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/var/lib/bitnami/redis/data'

volumes:
    redis_data:
      driver: local
    db_data: 
      driver: local